### ISSUE TITLE
SimpleX-Chat und Nostr Buttons

### ISSUE THREAD

**Issue by marc3linho** [Einundzwanzig-Podcast/einundzwanzig-portal#18]
Moin,
es wäre toll, wenn man auf der Meetup-Page auch einen Button für SimpleX und Nostr hätte.

![image](https://github.com/Einundzwanzig-Podcast/einundzwanzig-portal/assets/130232436/f1d85377-d5a6-4ce5-9a47-1055fd97460b)

**Comment by HolgerHatGarKeineNode** [comment]
@marc3linho Wurde hinzugefügt und ist nun im Formular für Meetups verfügbar.

**Comment by marc3linho** [comment]
Moin, dein Commit https://github.com/Einundzwanzig-Podcast/einundzwanzig-portal/commit/56278311918811d566d2c5418be6e6d88609174d fügt nur den SimpleX-Link ein. 
Ist der Nostr-Button an dieser Stelle nicht gewollt?

**Comment by HolgerHatGarKeineNode** [comment]
Hab ich glatt überlesen.
Ich setze Nostr auch mit ein und erweitere die API `/api/meetups` @dennisreimann 
Dann könnte man das auch auf einundzwanzig.space anzeigen.
