### ISSUE TITLE
Inhalte lassen sich nicht erstellen

### ISSUE THREAD

**Issue by xXxecutor** [Einundzwanzig-Podcast/einundzwanzig-portal#3]
Moin! Leider ist es mir aktuell nicht möglich, neue Inhalte zu erstellen, da die entsprechenden Buttons nicht funktionieren. Das Problem tritt überall auf, wo ich neue Inhalte hinzufügen will. Egal, ob neues Meetup, neue Stadt für Bücherschränke, neue Inhalte für die Bibliothek, neue Kurse oder Dozenten. Überall die direkte Weiterleitung zu /my-meetups, obwohl jeweils die offensichtlich korrekte Verlinkung für die Buttons hinterlegt ist. Andere Buttons wie "Mein Profil" funktionieren ohne Probleme.

**Comment by HolgerHatGarKeineNode** [comment]
Hast du auch bei `/my-meetups` einen der Meetups gewählt?
Damit Einträge im Backend gemacht werden können und wir den Zugriff für deine Meetups konfigurieren können, benötigt man mindestens ein Meetup.

Danach sollte man ins Backend gelangen und kann für das Meetup, das man unter `/my-meetups` ausgewählt hat Einträge eingeben.

Falls du dich für kein spezifischen Meetup entscheiden möchtest, nehme einfach irgeinen der Meetups und dann bekommst du Zugriff auf's Backend.

Werde den Hilfe-Text dazu auf dieser Seite erweitern, damit man besser erkennt warum man nun Weitergeleitet wurde.

**Comment by xXxecutor** [comment]
Okay, das ist tatsächlich etwas ungünstig gelöst. Aber danke für die Info, hat jetzt hingehauen. 😅
